name: 'Sponsors Action'
description: 'TODO'
author: 'James Ives <iam@jamesiv.es>'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'truck'
  color: 'purple'
inputs:
  template:
    description: 'TODO:'
    required: false

  token:
    description: >
      This option defaults to the repository scoped GitHub Token. 
      However if you need more permissions for things such as deploying to another repository, you can add a Personal Access Token (PAT) here. 
      This should be stored in the `secrets / with` menu **as a secret**.

      We recommend using a service account with the least permissions neccersary
      and when generating a new PAT that you select the least permission scopes required.

      [Learn more about creating and using encrypted secrets here.](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
